### ISSUE TITLE
Some assistance if possible !

### ISSUE THREAD

**Issue by StefanCiobanu1989** [pyguerder/bitbucket-pipelines-php74#5]
When the pipeline starts it always fails with 
`Caused by
PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'
/opt/atlassian/pipelines/agent/build/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:34
/opt/atlassian/pipelines/agent/build/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:25
/opt/atlassian/pipelines/agent/build/vendor/doctrine/dbal/src/Connection.php:323
/opt/atlassian/pipelines/agent/build/vendor/doctrine/dbal/src/Connection.php:387
/opt/atlassian/pipelines/agent/build/vendor/doctrine/dbal/src/Connection.php:349
/opt/atlassian/pipelines/agent/build/vendor/doctrine/dbal/src/Connection.php:274
/opt/atlassian/pipelines/agent/build/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:747
/opt/atlassian/pipelines/agent/build/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:557
/opt/atlassian/pipelines/agent/build/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:145
/opt/atlassian/pipelines/agent/build/vendor/doctrine/doctrine-bundle/Mapping/ClassMetadataFactory.php:19
/opt/atlassian/pipelines/agent/build/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:382
/opt/atlassian/pipelines/agent/build/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:251
/opt/atlassian/pipelines/agent/build/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:303
/opt/atlassian/pipelines/agent/build/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php:40
/opt/atlassian/pipelines/agent/build/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:780
/opt/atlassian/pipelines/agent/build/var/cache/test/ContainerYsNF4Mj/EntityManager_9a5be93.php:227
/opt/atlassian/pipelines/agent/build/src/CoreEventListeners/KernelRequestOverride.php:34
/opt/atlassian/pipelines/agent/build/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117
/opt/atlassian/pipelines/agent/build/vendor/symfony/event-dispatcher/EventDispatcher.php:230
/opt/atlassian/pipelines/agent/build/vendor/symfony/event-dispatcher/EventDispatcher.php:59
/opt/atlassian/pipelines/agent/build/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:151
/opt/atlassian/pipelines/agent/build/vendor/symfony/http-kernel/HttpKernel.php:132
/opt/atlassian/pipelines/agent/build/vendor/symfony/http-kernel/HttpKernel.php:78
/opt/atlassian/pipelines/agent/build/vendor/symfony/http-kernel/Kernel.php:199
/opt/atlassian/pipelines/agent/build/vendor/symfony/http-kernel/HttpKernelBrowser.php:65
/opt/atlassian/pipelines/agent/build/vendor/symfony/framework-bundle/KernelBrowser.php:172
/opt/atlassian/pipelines/agent/build/vendor/symfony/browser-kit/AbstractBrowser.php:402
/opt/atlassian/pipelines/agent/build/tests/DefaultControllerTest.php:21`

I have no idea how to fix this issue, below is my pipeline script 

> image: pyguerder/bitbucket-pipelines-php74
> pipelines:
>   default:
>     - step:
>         script:
>           #run mysql service
>           - service mysql start
>           - mysql -h localhost -u root -proot
>           #install composer dependecies
>           - composer install --no-interaction --no-progress --prefer-dist
>           #run unit tests
>           - ./vendor/bin/phpunit tests
>           #do whatever after unit test

it's pretty much based on yours but because i'm most likely a dumb ass i know i'm missing something. Some pointers would be much appreciated . Thank you !

**Comment by pyguerder** [comment]
@StefanCiobanu1989 I don't provide this kind of assistance because it is related to your application, not my Docker image.

It is clear that your application tries to access the database but does not provide the correct credentials. I suppose that you are using Symfony. Please check that the **MySQL** **password** is "root" in your .env or .env.local or parameters.yml

Best regards

**Comment by pyguerder** [comment]
Also, your line
`          - mysql -h localhost -u root -proot"`
does nothing. It should created a database:
`          - mysql -h localhost -u root -proot -e "CREATE DATABASE test;"`
and you should use that database name in your project configuration.

**Comment by StefanCiobanu1989** [comment]
Thank you !
